export const sampleData = [
  {
    name: "Wireless Earbuds",
    url: "https://example.com/wireless-earbuds",
    imageUrl: "https://images.unsplash.com/photo-1576160491696-df97e09168fd",
    price: "$59.99",
    affiliate_link: "https://affiliate.example.com/wireless-earbuds",
    rating: 4,
  },
  {
    name: "Smartwatch",
    url: "https://example.com/smartwatch",
    imageUrl: "https://images.unsplash.com/photo-1568336311279-7819b9e69f5b",
    price: "$129.99",
    affiliate_link: "https://affiliate.example.com/smartwatch",
    rating: 5,
  },
  {
    name: "Bluetooth Speaker",
    url: "https://example.com/bluetooth-speaker",
    imageUrl: "https://images.unsplash.com/photo-1583227390599-d8e75f6e85a2",
    price: "$39.99",
    affiliate_link: "https://affiliate.example.com/bluetooth-speaker",
    rating: 4,
  },
  {
    name: "Portable Charger",
    url: "https://example.com/portable-charger",
    imageUrl: "https://images.unsplash.com/photo-1573481062214-2a48cae3b55b",
    price: "$24.99",
    affiliate_link: "https://affiliate.example.com/portable-charger",
    rating: 3,
  },
  {
    name: "Laptop Stand",
    url: "https://example.com/laptop-stand",
    imageUrl: "https://images.unsplash.com/photo-1573496777869-957c7f97e9af",
    price: "$19.99",
    affiliate_link: "https://affiliate.example.com/laptop-stand",
    rating: 4,
  },
];
